/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as CampeonatosRouteImport } from './routes/campeonatos'
import { Route as EstadisticasRouteImport } from './routes/estadisticas'
import { Route as FixtureRouteImport } from './routes/fixture'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as ResolucionesRouteImport } from './routes/resoluciones'
import { Route as TablaRouteImport } from './routes/tabla'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedMiEquipoRouteImport } from './routes/_authenticated/mi-equipo'
import { Route as EquipoTeamIdRouteImport } from './routes/equipo.$teamId'
import { Route as PlanillaMatchIdRouteImport } from './routes/planilla.$matchId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const CampeonatosRoute = CampeonatosRouteImport.update({
  id: '/campeonatos',
  path: '/campeonatos',
  getParentRoute: () => rootRouteImport,
} as any)
const EstadisticasRoute = EstadisticasRouteImport.update({
  id: '/estadisticas',
  path: '/estadisticas',
  getParentRoute: () => rootRouteImport,
} as any)
const FixtureRoute = FixtureRouteImport.update({
  id: '/fixture',
  path: '/fixture',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ResolucionesRoute = ResolucionesRouteImport.update({
  id: '/resoluciones',
  path: '/resoluciones',
  getParentRoute: () => rootRouteImport,
} as any)
const TablaRoute = TablaRouteImport.update({
  id: '/tabla',
  path: '/tabla',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMiEquipoRoute = AuthenticatedMiEquipoRouteImport.update({
  id: '/mi-equipo',
  path: '/mi-equipo',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const EquipoTeamIdRoute = EquipoTeamIdRouteImport.update({
  id: '/equipo/$teamId',
  path: '/equipo/$teamId',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanillaMatchIdRoute = PlanillaMatchIdRouteImport.update({
  id: '/planilla/$matchId',
  path: '/planilla/$matchId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/campeonatos': typeof CampeonatosRoute
  '/estadisticas': typeof EstadisticasRoute
  '/fixture': typeof FixtureRoute
  '/reset-password': typeof ResetPasswordRoute
  '/resoluciones': typeof ResolucionesRoute
  '/tabla': typeof TablaRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/mi-equipo': typeof AuthenticatedMiEquipoRoute
  '/equipo/$teamId': typeof EquipoTeamIdRoute
  '/planilla/$matchId': typeof PlanillaMatchIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/campeonatos': typeof CampeonatosRoute
  '/estadisticas': typeof EstadisticasRoute
  '/fixture': typeof FixtureRoute
  '/reset-password': typeof ResetPasswordRoute
  '/resoluciones': typeof ResolucionesRoute
  '/tabla': typeof TablaRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/mi-equipo': typeof AuthenticatedMiEquipoRoute
  '/equipo/$teamId': typeof EquipoTeamIdRoute
  '/planilla/$matchId': typeof PlanillaMatchIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/campeonatos': typeof CampeonatosRoute
  '/estadisticas': typeof EstadisticasRoute
  '/fixture': typeof FixtureRoute
  '/reset-password': typeof ResetPasswordRoute
  '/resoluciones': typeof ResolucionesRoute
  '/tabla': typeof TablaRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/mi-equipo': typeof AuthenticatedMiEquipoRoute
  '/equipo/$teamId': typeof EquipoTeamIdRoute
  '/planilla/$matchId': typeof PlanillaMatchIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/campeonatos'
    | '/estadisticas'
    | '/fixture'
    | '/reset-password'
    | '/resoluciones'
    | '/tabla'
    | '/admin'
    | '/mi-equipo'
    | '/equipo/$teamId'
    | '/planilla/$matchId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/campeonatos'
    | '/estadisticas'
    | '/fixture'
    | '/reset-password'
    | '/resoluciones'
    | '/tabla'
    | '/admin'
    | '/mi-equipo'
    | '/equipo/$teamId'
    | '/planilla/$matchId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/campeonatos'
    | '/estadisticas'
    | '/fixture'
    | '/reset-password'
    | '/resoluciones'
    | '/tabla'
    | '/_authenticated/admin'
    | '/_authenticated/mi-equipo'
    | '/equipo/$teamId'
    | '/planilla/$matchId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  CampeonatosRoute: typeof CampeonatosRoute
  EstadisticasRoute: typeof EstadisticasRoute
  FixtureRoute: typeof FixtureRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  ResolucionesRoute: typeof ResolucionesRoute
  TablaRoute: typeof TablaRoute
  EquipoTeamIdRoute: typeof EquipoTeamIdRoute
  PlanillaMatchIdRoute: typeof PlanillaMatchIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campeonatos': {
      id: '/campeonatos'
      path: '/campeonatos'
      fullPath: '/campeonatos'
      preLoaderRoute: typeof CampeonatosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/estadisticas': {
      id: '/estadisticas'
      path: '/estadisticas'
      fullPath: '/estadisticas'
      preLoaderRoute: typeof EstadisticasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fixture': {
      id: '/fixture'
      path: '/fixture'
      fullPath: '/fixture'
      preLoaderRoute: typeof FixtureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resoluciones': {
      id: '/resoluciones'
      path: '/resoluciones'
      fullPath: '/resoluciones'
      preLoaderRoute: typeof ResolucionesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tabla': {
      id: '/tabla'
      path: '/tabla'
      fullPath: '/tabla'
      preLoaderRoute: typeof TablaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/mi-equipo': {
      id: '/_authenticated/mi-equipo'
      path: '/mi-equipo'
      fullPath: '/mi-equipo'
      preLoaderRoute: typeof AuthenticatedMiEquipoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/equipo/$teamId': {
      id: '/equipo/$teamId'
      path: '/equipo/$teamId'
      fullPath: '/equipo/$teamId'
      preLoaderRoute: typeof EquipoTeamIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/planilla/$matchId': {
      id: '/planilla/$matchId'
      path: '/planilla/$matchId'
      fullPath: '/planilla/$matchId'
      preLoaderRoute: typeof PlanillaMatchIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedMiEquipoRoute: typeof AuthenticatedMiEquipoRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedMiEquipoRoute: AuthenticatedMiEquipoRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  CampeonatosRoute: CampeonatosRoute,
  EstadisticasRoute: EstadisticasRoute,
  FixtureRoute: FixtureRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  ResolucionesRoute: ResolucionesRoute,
  TablaRoute: TablaRoute,
  EquipoTeamIdRoute: EquipoTeamIdRoute,
  PlanillaMatchIdRoute: PlanillaMatchIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
